### ISSUE TITLE
how to compile compenents 

### ISSUE THREAD

**Issue by brianray** [jonrossclaytor/kubeflow-mlb#1]
hey @jonrossclaytor, is there any easy way to rebuild the containers.

**Comment by jonrossclaytor** [comment]
@brianray after you clone the repo, you'll need to build an image locally for each component.  I think you have to do this manually but the Dockerfile is there for each of them.  Once you've built the image locally, push it to GCR.  Now, the image can be referenced in the pipeline definition.  

The image is then "compiled" and becomes a container upon runtime by Kubeflow when you execute the pipeline. 

Let me know if this doesn't answer your question ..

**Comment by brianray** [comment]
works thx!
